Repository wecode-bootcamp-korea/46-2nd-SUMMIT-frontend, pull requests merged in 2023-06, with the labels that each got.

#1 [46기 백지율] Button 컴포넌트 UI 구현
  src/components/Button/Button.js
  src/components/Button/Button.jsx
Labels: 멘토 리뷰 요청

#3 [46기 백지율] Login 페이지 UI 구현
  public/image/theatre.jpg
  src/pages/Login/Login.js
  src/pages/Login/Login.jsx
Labels: 멘토 리뷰 요청

#8 [46기 장건웅]Add: ShowList-layout
  package-lock.json
  package.json
  public/data/showData.json
  public/images/Main/comedy.png
  public/images/Main/fear.png
  public/images/Main/friendship.png
  public/images/Main/romance.png
  src/assets/heart.png
  src/assets/sample.png
  src/assets/search.png
  src/components/ShowCard/ShowCard.js
  src/components/ShowCard/ShowCard.jsx
  src/pages/ShowList/ShowList.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청

#4 [46기 조수진] ADD: 결제페이지 UI 구현
  src/pages/Checkout/Checkout.js
  src/pages/Checkout/Checkout.jsx
  src/pages/Checkout/Payment.jsx
  src/pages/Checkout/Subject.jsx
  src/pages/Checkout/TermList.jsx
Labels: 멘토 리뷰 요청

#5 [46기 백지율] Checkbox 컴포넌트 UI 구현
  public/image/checked.png
  public/image/unchecked.png
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/Checkbox.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#7 [46기 장건웅]Add: ShowDetail-layout
  package-lock.json
  package.json
  public/data/seatData.json
  public/data/showData.json
  src/assets/checked.png
  src/assets/like.png
  src/components/ShowDetail/SeatBox.js
  src/components/ShowDetail/SeatBox.jsx
  src/pages/ShowDetail/ShowDetail.js
  src/pages/ShowDetail/ShowDetail.jsx
Labels: Conflict 해결 완료

#12 [46기 조수진] ADD: 결제페이지 기능구현
  src/pages/Checkout/Checkout.js
  src/pages/Checkout/Checkout.jsx
  src/pages/Checkout/Payment.jsx
  src/pages/Checkout/TermList.jsx
Labels: 멘토 리뷰 요청

#9 [46기 조수진] ADD: 커뮤니티페이지 레이아웃 구현
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/pages/Community/Community.js
  src/pages/Community/Community.jsx
  src/pages/Community/Component/Article.js
  src/pages/Community/Component/Article.jsx
  src/pages/Community/Component/Category.jsx
  src/pages/Community/Component/Debate.jsx
  src/pages/Community/Component/DebateCard.jsx
  src/pages/Community/Component/DebateDetail.js
  src/pages/Community/Component/DebateDetail.jsx
  src/pages/Community/Component/Detail.js
  src/pages/Community/Component/Detail.jsx
  src/pages/Community/Component/Dummy.jsx
  src/pages/Community/Component/Writing.js
  src/pages/Community/Component/Writing.jsx
Labels: 수정 완료

#10 [46기 옥준우] ADD: Footer 구현
  src/Router.js
  src/components/Footer/Footer.jsx
  src/pages/Main/Main.jsx
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#13 [46기 백지율] Add: Reservation 페이지 레이아웃 구현
  .gitignore
  package-lock.json
  package.json
  src/pages/Reservation/Component/Calendar/Calendar.js
  src/pages/Reservation/Component/Calendar/Calendar.jsx
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/Reservation.jsx
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#11 [46기 옥준우] ADD: Nav
  package-lock.json
  package.json
  src/Router.js
  src/assets/Logodmo.png
  src/components/Nav/Nav.jsx
  src/components/Searchbar.jsx
  src/pages/Main/Main.jsx
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#14 [46기 장건웅] Add: 로그인페이지에서 NAV, FOOTER 제거
  src/Container.js
  src/Router.js
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#15 [46기 백지율] Add: Register 페이지 레이아웃 구현
  .env
  public/image/seats.jpg
  src/Router.js
  src/pages/Register/Register.js
  src/pages/Register/Register.jsx
  src/pages/Register/components/CalendarFilter/CalendarFilter.js
  src/pages/Register/components/CalendarFilter/CalendarFilter.jsx
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#20 [46기 장건웅]Add: CustomHooks - UseOutsideClick 추가
  src/components/ShowDetail/SeatBox.jsx
  src/hooks/useOnClickOutside.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청

#21 [46기 백지율] Add: Router 전체 경로 수정
  package-lock.json
  src/Router.js
  src/pages/Login/Oauth/Oauth.js
  src/pages/Login/Oauth/Oauth.jsx
Labels: 멘토 리뷰 요청

#18 [46기 백지율] Add: 카카오 로그인 기능 구현
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
  src/config.js
  src/pages/Login/Login.jsx
  src/pages/Login/Oauth/Oauth.jsx
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#23 [46기 조수진] 모달창 컴포넌트
  src/components/Modal/Modal.js
  src/components/Modal/Modal.jsx
Labels: 멘토 리뷰 요청

#24 [46기 백지율] 카드 컴포넌트 레이아웃 및 기능 구현
  public/image/clickedHeart.ico
  public/image/unclickedHeart.ico
  src/Container.js
  src/components/Button/Button.js
  src/components/Button/Button.jsx
  src/components/ShowCard/ShowCard.js
  src/components/ShowCard/ShowCard.jsx
Labels: 멘토 리뷰 요청

#16 [46기 장건웅] Add: 검색기능 추가
  public/data/seatData.json
  public/data/showData.json
  src/Router.js
  src/components/Card/Card.js
  src/components/Card/Card.jsx
  src/components/CardList/CardList.js
  src/components/CardList/CardList.jsx
  src/components/Search/Search.js
  src/components/Search/Search.jsx
  src/pages/ShowDetail/ShowDetail.js
  src/pages/ShowDetail/ShowDetail.jsx
  src/pages/ShowDetail/components/SeatBox.js
  src/pages/ShowDetail/components/SeatBox.jsx
  src/pages/ShowList/ShowList.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청, 수정 완료

#25 [46기 장건웅]Add: recoil 추가 및 디테일페이지 수정
  .env
  package-lock.json
  package.json
  public/data/seatData.json
  public/data/showData.json
  public/data/showDataMock.json
  src/atom.js
  src/config.js
  src/index.jsx
  src/pages/ShowDetail/ShowDetail.jsx
  src/pages/ShowDetail/components/SeatBox.js
  src/pages/ShowDetail/components/SeatBox.jsx
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청, 수정 완료

#19 [46기 옥준우] feature/nav
  package-lock.json
  package.json
  src/components/Footer/Footer.js
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.js
  src/components/Nav/Nav.jsx
  src/components/Searchbar.jsx
  src/pages/Main/Main.jsx
Labels: 멘토 리뷰 요청

#26 [46기 백지율] Add: Nav 좋아요 기능 구현
  .env
  public/data/wishList.json
  src/components/Button/Button.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.jsx
  src/config.js
  src/pages/Login/Oauth/Oauth.jsx
Labels: 멘토 리뷰 요청

#27 [46기 백지율] Add: Login 및 Oauth 페이지 레이아웃 수정
  public/image/KakaoBtn.png
  src/pages/Login/Login.js
  src/pages/Login/Login.jsx
  src/pages/Login/Oauth/Oauth.js
  src/pages/Login/Oauth/Oauth.jsx
Labels: 멘토 리뷰 요청

#29 [46기 백지율] Add: register 페이지 fetch 코드 추가
  src/Container.js
  src/components/Modal/Modal.js
  src/config.js
  src/pages/Register/Register.js
  src/pages/Register/Register.jsx
  src/pages/Register/components/CalendarFilter/CalendarFilter.jsx
  src/pages/Register/handleDateForm.jsx
Labels: 멘토 리뷰 요청, 수정 완료

#30 [46기 장건웅]Add: 리스트페이지 필터 및 통신
  src/Router.js
  src/components/Button/Button.js
  src/components/Card/Card.js
  src/components/Card/Card.jsx
  src/config.js
  src/pages/ShowDetail/ShowDetail.jsx
  src/pages/ShowDetail/components/SeatBox.jsx
  src/pages/ShowList/Components/Drop.js
  src/pages/ShowList/Components/Drop.jsx
  src/pages/ShowList/ShowList.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청, 수정 완료

#31 [46기 백지율] Add: Reservation 페이지 Recoil 코드 추가
  public/data/seatData.json
  public/data/showDetail.json
  src/Recoil/ReservationAtom.jsx
  src/components/Checkbox/Checkbox.jsx
  src/components/Nav/Nav.jsx
  src/index.jsx
  src/pages/Reservation/Component/Calendar/Calendar.jsx
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/Reservation.jsx
  src/pages/ShowDetail/ShowDetail.jsx
  src/pages/ShowDetail/components/SeatBox.js
  src/pages/ShowDetail/components/SeatBox.jsx
Labels: 멘토 리뷰 요청, 수정 완료

#33 [46기 백지율] Modify: 카드 컴포넌트 좋아요 통신 코드 추가
  .env
  src/components/Card/Card.jsx
  src/config.js
Labels: 멘토 리뷰 요청, 수정 완료

#34 [46기 조수진] ADD: 결제페이지 recoil과 fetch통신기능 추가
  package-lock.json
  package.json
  src/config.js
  src/pages/Checkout/Checkout.js
  src/pages/Checkout/Checkout.jsx
  src/pages/Checkout/Payment.jsx
  src/pages/Checkout/Subject.jsx
Labels: 멘토 리뷰 요청

#35 [46기 조수진] ADD:커뮤니티 recoil 기능구현
  src/Recoil/CommunityAtom.jsx
  src/pages/Community/Community.jsx
  src/pages/Community/Component/Article.js
  src/pages/Community/Component/Article.jsx
  src/pages/Community/Component/Category.jsx
  src/pages/Community/Component/Debate.jsx
  src/pages/Community/Component/DebateCard.jsx
  src/pages/Community/Component/DebateDetail.js
  src/pages/Community/Component/DebateDetail.jsx
  src/pages/Community/Component/Detail.js
  src/pages/Community/Component/Detail.jsx
  src/pages/Community/Component/Dummy.jsx
  src/pages/Community/Component/Writing.jsx
  src/pages/Community/util/util.js
Labels: 멘토 리뷰 요청

#36 [46기 장건웅]Add: 페이지네이션 추가
  src/components/Card/Card.jsx
  src/config.js
  src/pages/ShowDetail/ShowDetail.jsx
  src/pages/ShowList/Components/Drop.jsx
  src/pages/ShowList/ShowList.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청, 수정 완료

#37 [46기 백지율] Modify: register 페이지 fetch 코드 수정
  src/pages/Register/Register.jsx
  src/pages/Register/handleDateForm.jsx
Labels: 멘토 리뷰 요청

#39 [46기 장건웅]fix:showDetail 로직수정
  src/pages/ShowDetail/ShowDetail.jsx
Labels: 멘토 리뷰 요청

#40 [46기 백지율] Add: 카드 컴포넌트 통신 코드 수정
  package-lock.json
  package.json
  src/components/Card/Card.js
  src/components/Card/Card.jsx
  src/components/CardList/CardList.jsx
  src/config.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청

#41 [46기 옥준우] main
  src/components/Nav/Nav.jsx
  src/pages/Main/components/Bestonboard.js
  src/pages/Main/components/Bestonmanager.js
  src/pages/Main/components/Bestonreview.js
  src/pages/Main/components/Carousel.js
  src/pages/Main/components/Categorytransfer.js
  src/pages/Main/components/Theathersituation.js
Labels: 멘토 리뷰 요청

#42 [46기 백지율] MODIFY: NAV 레이아웃 및 통신 코드 수정
  src/components/Nav/Nav.js
  src/components/Nav/Nav.jsx
  src/config.js
Labels: 멘토 리뷰 요청

#45 [46기 조수진] ADD: 결제페이지 기능구현
  .env
  src/config.js
  src/pages/Checkout/Checkout.jsx
  src/pages/Checkout/Subject.jsx
Labels: 멘토 리뷰 요청

#47 [46기 백지율] Add: reservation 페이지 기능 추가
  src/pages/Reservation/Reservation.jsx
Labels: 멘토 리뷰 요청

#44 [46기 장건웅]Modify:css 수정
  src/components/Footer/Footer.js
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.js
  src/components/Searchbar.jsx
  src/config.js
  src/pages/Community/Community.js
  src/pages/Main/components/Theathersituation.js
  src/pages/Reservation/Reservation.js
  src/pages/ShowDetail/ShowDetail.js
  src/pages/ShowDetail/ShowDetail.jsx
  src/pages/ShowDetail/components/SeatBox.js
  src/pages/ShowDetail/components/SeatBox.jsx
  src/pages/ShowList/ShowList.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청

#48 [46기 장건웅] Fix: 페이지네이션 로직 수정
  src/pages/ShowList/Components/Drop.jsx
  src/pages/ShowList/ShowList.js
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청

#50 [46기 장건웅]Fix/community css
  src/pages/Community/Community.js
  src/pages/Community/Component/Writing.js
  src/pages/ShowDetail/ShowDetail.js
  src/pages/ShowList/ShowList.js
Labels: 멘토 리뷰 요청

#51 [46기 옥준우] CSS configure
  src/assets/MAP.jpg
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/Search/Search.js
  src/components/Searchbar.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/components/Bestonboard.js
  src/pages/Main/components/Bestonmanager.js
  src/pages/Main/components/Bestonreview.js
  src/pages/Main/components/Poster.js
  src/pages/Main/components/Poster.jsx
  src/pages/Main/components/Theathersituation.js
  src/pages/ShowList/ShowList.js
Labels: 멘토 리뷰 요청

#49 [46기 백지율] Modify; wishlist flow 및 레이아웃 수정
  src/Recoil/ShowListAtom.jsx
  src/Recoil/WishListAtom.jsx
  src/components/Card/Card.js
  src/components/Card/Card.jsx
  src/components/Nav/Nav.jsx
  src/pages/ShowList/ShowList.jsx
Labels: 멘토 리뷰 요청, Conflict 해결 완료

#53 [46기 장건웅]Fix: 스타일 수정
  src/Router.js
  src/components/Checkbox/Checkbox.js
  src/pages/Checkout/Checkout.js
  src/pages/Community/Community.js
  src/pages/Register/Register.js
  src/pages/Reservation/Component/Calendar/Calendar.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/Reservation.jsx
  src/pages/ShowDetail/components/SeatBox.js
Labels: 멘토 리뷰 요청

#55 [46기 백지율] ADD: showList fetch 코드 추가
  src/Recoil/ShowDetailAtom.jsx
  src/components/Nav/Nav.jsx
  src/pages/ShowDetail/ShowDetail.js
  src/pages/ShowDetail/ShowDetail.jsx
Labels: 멘토 리뷰 요청

#57 [46기 장건웅]Fix: 쿼리스트링 로직 수정
  src/pages/ShowList/Components/Drop.jsx
Labels: 멘토 리뷰 요청

#56 [46기 조수진] MODIFY:CSS 수정
  src/pages/Community/Community.js
Labels: 멘토 리뷰 요청
